oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /

vendor_maxfirst:
    resource: "@VendorMaxfirstBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
